export { default as camera } from "./camera.webp";
export { default as tv } from "./tv.webp";
export { default as headphone } from "./headphone.webp";
export { default as speaker } from "./speaker.webp";
export { default as watch } from "./watch.webp";
export { default as tab } from "./tab.jpg";
export { default as tab1 } from "./tab1.jpg";
export { default as tab2 } from "./tab2.jpg";
export { default as tab3 } from "./tab3.jpg";
